// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV15NACuVAwqURJ8dHCff-8s3xkTh8iq0',
    appId: '1:306161590701:web:8120cfedae98667ce7c124',
    messagingSenderId: '306161590701',
    projectId: 'face-auth-581c9',
    authDomain: 'face-auth-581c9.firebaseapp.com',
    storageBucket: 'face-auth-581c9.firebasestorage.app',
    measurementId: 'G-63JG0ZQJ5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMT2Hv3NXTa4isYDvxMCXiuDVXZcVJSZ8',
    appId: '1:306161590701:android:af533fed82756829e7c124',
    messagingSenderId: '306161590701',
    projectId: 'face-auth-581c9',
    storageBucket: 'face-auth-581c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNypk76pnwsvYeV0YI-nr5jhNfjEpTsNg',
    appId: '1:306161590701:ios:57852bf2b465a1c6e7c124',
    messagingSenderId: '306161590701',
    projectId: 'face-auth-581c9',
    storageBucket: 'face-auth-581c9.firebasestorage.app',
    iosBundleId: 'com.example.faceAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNypk76pnwsvYeV0YI-nr5jhNfjEpTsNg',
    appId: '1:306161590701:ios:57852bf2b465a1c6e7c124',
    messagingSenderId: '306161590701',
    projectId: 'face-auth-581c9',
    storageBucket: 'face-auth-581c9.firebasestorage.app',
    iosBundleId: 'com.example.faceAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV15NACuVAwqURJ8dHCff-8s3xkTh8iq0',
    appId: '1:306161590701:web:fc8159fb06e9f3ede7c124',
    messagingSenderId: '306161590701',
    projectId: 'face-auth-581c9',
    authDomain: 'face-auth-581c9.firebaseapp.com',
    storageBucket: 'face-auth-581c9.firebasestorage.app',
    measurementId: 'G-LFHL02M215',
  );
}
